
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 09 22:58:36 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 14;
  public static final int DIVIDE = 40;
  public static final int CONST = 27;
  public static final int ASSIGNMENT = 19;
  public static final int RIGHT_SQUARE_BRACKET = 7;
  public static final int NOT_EQUAL = 26;
  public static final int GREATER = 33;
  public static final int SEMI = 5;
  public static final int LESS = 29;
  public static final int MINUS = 25;
  public static final int AND = 28;
  public static final int OR = 38;
  public static final int COMMA = 10;
  public static final int INC = 32;
  public static final int LESS_EQUAL = 35;
  public static final int PLUS = 24;
  public static final int MULTIPLY = 20;
  public static final int LEFT_CURLY_BRACKET = 23;
  public static final int LEFT_ROUND_BRACKET = 3;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 34;
  public static final int LEFT_SQUARE_BRACKET = 6;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int NUMBER = 12;
  public static final int IDENT = 13;
  public static final int VOID = 11;
  public static final int findAny = 17;
  public static final int COLON = 18;
  public static final int POINT = 37;
  public static final int READ = 30;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 15;
  public static final int DEC = 39;
  public static final int MODUO = 21;
  public static final int RIGHT_CURLY_BRACKET = 22;
  public static final int DO = 36;
  public static final int PRINT = 31;
  public static final int RIGHT_ROUND_BRACKET = 4;
}

