
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Apr 15 22:10:14 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 16;
  public static final int DIVIDE = 47;
  public static final int CONST = 29;
  public static final int ASSIGNMENT = 21;
  public static final int RIGHT_SQUARE_BRACKET = 7;
  public static final int NOT_EQUAL = 28;
  public static final int CONTINUE = 44;
  public static final int GREATER = 37;
  public static final int SEMI = 5;
  public static final int LESS = 31;
  public static final int MINUS = 27;
  public static final int AND = 30;
  public static final int RECORD = 42;
  public static final int OR = 45;
  public static final int COMMA = 11;
  public static final int INC = 35;
  public static final int LESS_EQUAL = 40;
  public static final int PLUS = 10;
  public static final int MULTIPLY = 22;
  public static final int LEFT_CURLY_BRACKET = 26;
  public static final int IF = 18;
  public static final int LEFT_ROUND_BRACKET = 3;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 39;
  public static final int LEFT_SQUARE_BRACKET = 6;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int NUMBER = 14;
  public static final int BREAK = 33;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int COLON = 20;
  public static final int ELSE = 19;
  public static final int POINT = 43;
  public static final int ENUM = 32;
  public static final int READ = 34;
  public static final int GOTO = 36;
  public static final int WHILE = 38;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 17;
  public static final int DEC = 46;
  public static final int MODUO = 23;
  public static final int RIGHT_CURLY_BRACKET = 25;
  public static final int DO = 41;
  public static final int PRINT = 12;
  public static final int RIGHT_ROUND_BRACKET = 4;
}

